name: Linting code

on: [pull-request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "src/"
      - uses: tj-actions/eslint-changed-files@v25.3.2
        with:
          config_path: "./eslint.config.mjs"
