name: Build and Deploy to Netlify
on:
  workflow_dispatch:
jobs:
  netlify-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './netlify-publish'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Message App from GitHub Actions"
          fails-without-credentials: true
          github-deployment-environment: 'production'


        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1