name: Build and push Docker image to GHCR - development

on:
  push:
    tags: ["v*"]

  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string
      # branch:
      #   type: choice
      #   required: true
      #   options:
      #     - frontend
      #     - backend
      #     - production
      #   default: 'frontend'


jobs:
  backend_dev:
    name: backend dev
    # if: ${{ inputs.branch == 'backend' }}
    uses: ./.github/workflows/cd-ghcr-callable.yml
    with: 
      DOCKER_PATH: ./Backend/Dockerfile
      target: "development"
      new-version-tag: ${{ inputs.new-version-tag }}
      environment: "development"

  frontend_dev:
    name: frontend dev
    # if: ${{ inputs.environment == 'development-frontend' }}
    uses: ./.github/workflows/cd-ghcr-callable.yml
    with: 
      DOCKER_PATH: ./Frontend/Dockerfile
      target: "development"
      new-version-tag: ${{ inputs.new-version-tag }}
      environment: "development"

  # app_prod:
  #   name: application production
  #   if: ${{ inputs.environment == 'production' }}
  #   uses: ./.github/workflows/cd-ghcr-callable.yml
  #   with:
  #     DOCKER_PATH: ./Backend/Dockerfile
  #     target: "production"
  #     new-version-tag: ${{ inputs.new-version-tag }}
  #     environment: "production"