name: Build and push production Docker image to GHCR

on:
  push:
    tags: ["v*"]

  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string

jobs:
  app_prod:
    name: application production
    uses: ./.github/workflows/cd-ghcr-callable.yml
    with:
      DOCKER_PATH: ./Backend/Dockerfile
      target: "production"
      new-version-tag: ${{ inputs.new-version-tag }}
      environment: "production"