name: Build and Push Backend Docker Image to GAR

on:
  push:
    tags: ["v*"]
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string

jobs:
  backend-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Push Docker Image to GAR
        uses: a94763075/push-to-gar-github-action@v0.3.1
        with:
          gcloud_service_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: 'mern-messaging-app-487603'
          registry: 'us-central1'
          repository: 'message-app-backend-dev'
          image_name: 'backend-dev'
          image_tags: 'latest,${{inputs.new-version-tag}}'
          dockerfile: './Backend/Dockerfile'
          target: 'development'
          free_docker_build_parameter: '--no-cache'