name: Backend deploy to GCP 

on:
  workflow_run:
    workflows: [Build and Push Backend Docker Image to GAR]
    types:
      - completed
  workflow_dispatch:

jobs:
  gcp-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v6'
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to GCP
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          service: 'message-app-backend-dev'
          image: 'us-central1-docker.pkg.dev/mern-messaging-app-487603/message-app-backend-dev/backend-dev:latest'
          env_vars: |
            JWT_SECRET=${{secrets.JWT_SECRET_KEY}}
            PORT=3000
            NODE_ENV=development

      - name: Use output
        run: 'curl "${{ steps.deploy.outputs.url }}"'
