name: Build and Push Backend Docker Image to GAR - development

on:
  push:
    tags: ["v*"]
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      new-version-tag:
        required: true
        type: string
env:
  PROJECT_ID: "mern-messaging-app-487603"
  GAR_REPO: "message-app-backend-dev"
  IMAGE_NAME: "backend-dev"
  LOCATION: "us-central1"

jobs:
  backend-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.4

      - name: Configure Docker Client for Gcloud
        run: gcloud auth configure-docker ${{env.LOCATION}}-docker.pkg.dev --quiet
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} --target development ./Backend

      - name: Push Docker Image to GAR
        run: |
          IFS=',' read -ra TAGS <<< "latest,${{ inputs.new-version-tag }}"
          for tag in "${TAGS[@]}"; do
            docker tag ${{env.IMAGE_NAME}} ${{env.LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE_NAME}}:$tag
            docker push ${{env.LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE_NAME}}:$tag
          done
        shell: bash
