name: Frontend development deploy to Render

on:
  workflow_run:
    workflows: [Build and push Frontend Docker image to GHCR - development]
    types:
      - completed
  workflow_dispatch:

jobs:
  render-deploy-dev-frontend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: check script
        run: npm run
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.3
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK_DEV }}
          image-url: ghcr.io/phuongle1911/mern-messaging-app-development:latest
          docker-repo-prefix: ghcr.io
          wait-for-deployment: true
          render-api-key: ${{ secrets.RENDER_API_KEY }}
