name: Linting code

on:
  pull_request:
    types: [opened, reopened]

jobs:
  eslint_backend:
    name: eslint backend
    uses: ./.github/workflows/ci-linting-callable.yml
    with:
      branch_name: 'backend'
      eslint_dir: 'Backend/'
      
  eslint_frontend:
    name: eslint frontend
    uses: ./.github/workflows/ci-linting-callable.yml
    with:
      branch_name: 'frontend'
      eslint_dir: 'Frontend/'
