name: Linting code

on:
  pull_request:
    types: [opened, reopened]

jobs:
  eslint-backend:
    name: eslint backend
    if: github.head_ref === 'backend'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "/Backend/src"
      - uses: tj-actions/eslint-changed-files@v25.3.2
        with:
          config_path: "./eslint.config.mjs"

    eslint-frontend:
      name: eslint frontend
      if: github.head_ref === 'frontend'
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v6
        - uses: reviewdog/action-eslint@v1.34.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review # Change reporter.
            eslint_flags: "/Frontend/src"
        - uses: tj-actions/eslint-changed-files@v25.3.2
          with:
            config_path: "./eslint.config.mjs"
