name: Linting code

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-github-api:
    name: check github api response
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - run: echo "head_ref output is ${{github.head_ref}}"
  eslint-backend:
    name: eslint backend
    if: contains(github.head_ref,'backend') === true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "/Backend"
      - uses: tj-actions/eslint-changed-files@v25.3.2
        with:
          config_path: "./eslint.config.mjs"

    eslint-frontend:
      name: eslint frontend
      if: contains(github.head_ref,'frontend') === true
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v6
        - uses: reviewdog/action-eslint@v1.34.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            reporter: github-pr-review # Change reporter.
            eslint_flags: "/Frontend"
        - uses: tj-actions/eslint-changed-files@v25.3.2
          with:
            config_path: "./eslint.config.mjs"
