name: Run project tests

on:
  pull_request:
    types: [opened, reopened]


jobs:
  backend_tests:
    name: backend tests
    if: contains(github.head_ref,'backend')
    uses: ./.github/workflows/ci-test-callable.yml
    with:
      testDirectory: "Backend/"
      reportFilePath: "/Backend/reports/jest-junit.xml"

  frontend_tests:
    name: frontend tests
    if: contains(github.head_ref,'frontend')
    uses: ./.github/workflows/ci-test-callable.yml
    with:
      testDirectory: "Frontend/"
      reportFilePath: "Frontend/reports/vitest-junit.xml"
