name: Project test callable workflow

on:
  workflow_call:
    inputs:
      testDirectory:
        required: true
        type: string


jobs:
  test_runner:
    name: test runner
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout or clone a copy of the repo to the action runner
        uses: actions/checkout@v6
      
      - name: Direct to test directory and run test
        run: |
          cd ${{ inputs.testDirectory }}
          npm ci
          npm run test:report

      - name: Confirm that new test output file exists
        run: |
          cd ${{ inputs.testDirectory }}
          ls

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            ${{ inputs.testDirectory }}reports/jest-junit.xml

      