name: Remove untagged Docker images

on:
  registry_package:
    types: [published]

  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'mern-messaging-app'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
          token: ${{ github.token }}