name: Remove untagged Docker images

on:
  registry_package:
    types: [published]

  schedule:
    - cron: "0 9 1,8,15,22,29 * *"


  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
      - name: delete untagged images in development package
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'mern-messaging-app-development'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
          token: ${{ github.token }}
      - name: delete untagged images in production package
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: 'mern-messaging-app-production'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
          token: ${{ github.token }}
      